development:
  adapter: postgresql
  pool: 5
  database: mh_development

test:
  adapter: postgresql
  pool: 5
  database: mh_test

production:
  adapter: postgresql
  pool: 5
  database: mh_production